---
# We have to requery the permissions for each grant because deleting an index
# results in other permissions getting indexes reassigned so there are no gaps.
- name: Get all permissions
  uri:
    url: "{{ _solr_cluster_url }}/solr/admin/authorization"
    force_basic_auth: true
    user: "{{ _solr_admin_user }}"
    password: "{{ _solr_admin_password }}"
    method: GET
    headers:
      Content-Type: "application/json"
    return_content: yes
    status_code:
      - 200
      - 201
  register: _permission_list
  until: _permission_list.status == 200
  retries: 3
  delay: 30

# Likewise, we also sort all permissions by index in *reverse* so we delete them
# in an order which doesn't affect the index of yet, to-be-deleted permissions.
- name: Get grants only for the current collection and permission
  set_fact:
    _collection_grant_for_perm: "{{ _permission_list.json.authorization.permissions \
      | selectattr('collection','defined') \
      | selectattr('collection', '==', _collection) \
      | selectattr('name','defined') \
      | selectattr('name', '==', _permission) \
      | selectattr('index','defined') \
      | sort(attribute='index') \
      | reverse \
      | list }}"

# It doesn't appear the API allows for deleting multiple indexes at once. So,
# Solr make this harder for us, but easier for them.
- name: Delete grants
  uri:
    url: "{{ _solr_cluster_url }}/solr/admin/authorization"
    force_basic_auth: true
    user: "{{ _solr_admin_user }}"
    password: "{{ _solr_admin_password }}"
    method: POST
    headers:
      Content-Type: "application/json"
    return_content: yes
    status_code:
      - 200
      - 201
    body_format: json
    body: |
      {
        "delete-permission": "{{ _grant.index }}"
      }
  loop: "{{ _collection_grant_for_perm | default([]) }}"
  loop_control:
    loop_var: _grant
    label: "{{ _permission }} for {{ _collection }} at {{ _grant.index }}"
