---
- name: Create the mysql service
  k8s:
    definition: |
      ---
      apiVersion: v1
      kind: Service
      metadata:
        name: {{ service.name | default(_mysql_cluster_full_name) }}
        labels:
          app.kubernetes.io/managed-by: "flightdeck-operator"
          app.kubernetes.io/created-by: "controller-manager"
          app.kubernetes.io/name: "MySQLCluster"
          app.kubernetes.io/instance: "{{ ansible_operator_meta.name }}"
          app.kubernetes.io/part-of: "{{ _mysql_cluster_full_name }}"
          flightdeck.ten7.io/mysqlcluster: "{{ ansible_operator_meta.name }}"
      spec:
        clusterIP: None
        ports:
          - name: mysql
            port: {{ service.port | default('3306') }}
            protocol: TCP
        selector:
          app.kubernetes.io/name: "MySQLCluster"
          app.kubernetes.io/component: "mysql"
          flightdeck.ten7.io/mysqlcluster: "{{ ansible_operator_meta.name }}"
    namespace: "{{ ansible_operator_meta.namespace }}"
