---
- name: Create memcache configmap
  k8s:
    definition: |
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: {{ _memcache_cluster_full_name }}
        labels:
          app.kubernetes.io/managed-by: "flightdeck-operator"
          app.kubernetes.io/created-by: "controller-manager"
      data:
        flightdeck-memcache.yml: |
          flightdeck_memcache:
      {% if flightdeck_debug | default(false) %}
            flightdeck_debug: yes
      {% endif %}
            port: "{{ service.port | default('11211') }}"
            memory: "{{ memory | default('256') }}"
            threads: "{{ threads | default('4') }}"
    namespace: "{{ ansible_operator_meta.namespace }}"
