---
- name: Generate the cluster name
  set_fact:
    _memcache_cluster_full_name: "{{ fullname_override | default(ansible_operator_meta.name + '-memcachecluster') }}"

- name: Work with configmaps
  include_tasks: 'configmaps.yml'
- name: Work with the statefulsets
  include_tasks: 'statefulsets.yml'
- name: Work with the services
  include_tasks: 'services.yml'
