- name: Create the solr service
  k8s:
    definition: |
      ---
      apiVersion: v1
      kind: Service
      metadata:
        name: {{ _solr_cluster_full_name }}
        labels:
          app.kubernetes.io/managed-by: "flightdeck-operator"
          app.kubernetes.io/created-by: "controller-manager"
          app.kubernetes.io/name: "SolrCluster"
          app.kubernetes.io/component: "search"
          app.kubernetes.io/instance: "{{ ansible_operator_meta.name }}"
          app.kubernetes.io/part-of: "{{ _solr_cluster_full_name }}"
          flightdeck.ten7.io/solrcluster: "{{ ansible_operator_meta.name }}"
      spec:
        ports:
          - name: "solr"
            port: {{ port | default('8983') }}
            protocol: TCP
        selector:
          app.kubernetes.io/name: "SolrCluster"
          app.kubernetes.io/component: "search"
          flightdeck.ten7.io/solrcluster: "{{ ansible_operator_meta.name }}"
    namespace: "{{ ansible_operator_meta.namespace }}"
