- name: Create the zookeeper service
  k8s:
    definition: |
      ---
      apiVersion: v1
      kind: Service
      metadata:
        name: {{ _zookeeper_cluster_full_name }}
        labels:
          app.kubernetes.io/managed-by: "flightdeck-operator"
          app.kubernetes.io/created-by: "controller-manager"
          app.kubernetes.io/name: "ZookeeperCluster"
          app.kubernetes.io/component: "clustering"
          app.kubernetes.io/instance: "{{ ansible_operator_meta.name }}"
          app.kubernetes.io/part-of: "{{ _zookeeper_cluster_full_name }}"
          flightdeck.ten7.io/zookeepercluster: "{{ ansible_operator_meta.name }}"
      spec:
        ports:
          - name: "zookeeper-client"
            port: {{ zookeeper_client_port | default('2181') }}
            protocol: TCP
          - name: "zookeeper-quorum"
            port: {{ quorum_port | default('2888') }}
            protocol: TCP
          - name: "zookeeper-leader"
            port: {{ leader_port | default('3888') }}
            protocol: TCP
        selector:
          app.kubernetes.io/name: "ZookeeperCluster"
          app.kubernetes.io/component: "clustering"
          flightdeck.ten7.io/zookeepercluster: "{{ ansible_operator_meta.name }}"
    namespace: "{{ ansible_operator_meta.namespace }}"
