---
- name: Generate the cluster name
  set_fact:
    _memcache_cluster_full_name: "{{ fullname_override | default(ansible_operator_meta.name + 'memcachecluster') }}"

- name: Delete the memcache service
  k8s:
    api_version: "v1"
    kind: "Service"
    name: "{{ service.name | default(_memcache_cluster_full_name) }}"
    namespace: "{{ ansible_operator_meta.namespace }}"
    state: absent

- name: Delete the memcache statefulset
  k8s:
    api_version: "apps/v1"
    kind: "StatefulSet"
    name: "{{ _memcache_cluster_full_name }}"
    namespace: "{{ ansible_operator_meta.namespace }}"
    state: absent

- name: Delete the memcache configmap
  k8s:
    api_version: "v1"
    kind: "ConfigMap"
    name: "{{ _memcache_cluster_full_name }}"
    namespace: "{{ ansible_operator_meta.namespace }}"
    state: absent
