- name: Get the solr user secret name
  set_fact:
    _solr_user_secret_name: "{{ secret | default(_solr_user_full_name + '-auth') }}"
- name: Check if the solr user secret already exists
  set_fact:
    _solr_user_secret_def: "{{ lookup('k8s', kind='secret', namespace=ansible_operator_meta.namespace, resource_name=_solr_user_secret_name) }}"

- name: Get the solr user password
  set_fact:
    _solr_user_password: "\
      {% if _solr_user_secret_def.data['password'] is not defined %}\
      {{ lookup('password', '/dev/null chars=ascii_letters,digits,hexdigits,punctuation length=20') }}\
      {% else %}\
      {{ _solr_user_secret_def.data['password'] | b64decode }}\
      {% endif %}"

- name: Create solr user secret
  k8s:
    definition: |
      apiVersion: v1
      data:
        password: "{{ _solr_user_password | b64encode }}"
      kind: Secret
      metadata:
        name: {{ _solr_user_secret_name }}
        labels:
          app.kubernetes.io/managed-by: "flightdeck-operator"
          app.kubernetes.io/created-by: "controller-manager"
          app.kubernetes.io/name: "SolrCluster"
          app.kubernetes.io/instance: "{{ ansible_operator_meta.name }}"
          app.kubernetes.io/part-of: "{{ _solr_cluster_full_name }}"
          flightdeck.ten7.io/solrcluster: "{{ ansible_operator_meta.name }}"
      type: Opaque
    namespace: "{{ ansible_operator_meta.namespace }}"
  when:
    - "(_solr_user_secret_def | length) < 1"
