# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/flightdeck.t7.io_mysqlclusters.yaml
- bases/flightdeck.t7.io_mysqldatabases.yaml
- bases/flightdeck.t7.io_mysqlusers.yaml
- bases/flightdeck.t7.io_memcacheclusters.yaml
- bases/flightdeck.t7.io_phpapplications.yaml
- bases/flightdeck.t7.io_htpasswds.yaml
- bases/flightdeck.t7.io_phproutes.yaml
- bases/flightdeck.t7.io_phpcronjobs.yaml
- bases/flightdeck.t7.io_solrclusters.yaml
- bases/flightdeck.t7.io_solrcollections.yaml
- bases/flightdeck.t7.io_zookeeperclusters.yaml
- bases/flightdeck.t7.io_solrconfigsets.yaml
- bases/flightdeck.t7.io_solrroles.yaml
- bases/flightdeck.t7.io_solrusers.yaml
# +kubebuilder:scaffold:crdkustomizeresource
