apiVersion: flightdeck.t7.io/v1
kind: PhpRoute
metadata:
  name: "apex"
spec:
  phpApplication: "drupal"
  tls:
    state: yes
    issuer: "lets-encrypt-prod"
  auth:
    state: yes
    htpasswd: "muffy-example-com"
  rules:
    - host: "muffy.example.com"
      paths:
        - path: "/"
