apiVersion: flightdeck.t7.io/v1
kind: ZookeeperCluster
metadata:
  name: "fdo-sample"
spec:
  replicas: 3
  persistence:
    enabled: true
    size: "1Gi"
    storageClass: "rook-cephfs"
    accessModes:
      - "ReadWriteOnce"
  service:
    name: 'zookeeper'
    clientPort: 2181
    quorumPort: 2888
    leaderPort: 3888
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/os
            operator: In
            values:
              - linux
