apiVersion: flightdeck.t7.io/v1
kind: MySQLCluster
metadata:
  name: fdo
  namespace: default
spec:
  persistence:
    enabled: yes
    size: 20Gi
  replicas: 3
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
           - matchExpressions:
             - key: kubernetes.io/os
               operator: In
               values:
                 - linux
  storageClass: "rook-cephfs"
