apiVersion: flightdeck.t7.io/v1
kind: MemcacheCluster
metadata:
  name: fdo-memcache
  namespace: default
spec:
  replicas: 3
  memory: "128"  # Memory is in MB.
  threads: "4"
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
           - matchExpressions:
             - key: kubernetes.io/os
               operator: In
               values:
                 - linux
  service:
    name: 'memcache'
    port: 11211
