apiVersion: flightdeck.t7.io/v1
kind: SolrCluster
metadata:
  name: "fdo"
spec:
  zookeeperCluster:
    name: "fdo"
    namespace: "default"
  replicas: 3
  persistence:
    enabled: true
    size: "5Gi"
    storageClass: "rook-cephfs"
    accessModes:
      - "ReadWriteOnce"
  solrAdmin:
    user: solr
    secret: "solr-admin-secret"
  service:
    name: 'solr'
    port: 8987
