apiVersion: flightdeck.t7.io/v1
kind: Htpasswd
metadata:
  name: "muffy-t7test-io"
spec:
  logins:
    - name: "my-user"
      secret: "existing-secret-name"   # If the secret exists, the content of the `password` key.
    - name: "another-user"             # Generates a new secret and a random password.
