apiVersion: flightdeck.t7.io/v1
kind: MySQLCluster
metadata:
  name: fdo
  namespace: default
spec:
  persistence:
    enabled: true
    size: "10Gi"
    storageClass: "rook-cephfs"
    accessModes:
      - "ReadWriteOnce"
  replicas: 3
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
           - matchExpressions:
             - key: kubernetes.io/os
               operator: In
               values:
                 - linux
  storageClass: "rook-cephfs"
  service:
    name: "fdo-mysqlcluster"  # Defaults to the CRD name + '-mysqlcluster'.
    port: 3306
