# permissions for end users to view htpasswds.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: htpasswd-viewer-role
rules:
- apiGroups:
  - flightdeck.t7.io
  resources:
  - htpasswds
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - flightdeck.t7.io
  resources:
  - htpasswds/status
  verbs:
  - get
