# permissions for end users to edit htpasswds.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: htpasswd-editor-role
rules:
- apiGroups:
  - flightdeck.t7.io
  resources:
  - htpasswds
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - flightdeck.t7.io
  resources:
  - htpasswds/status
  verbs:
  - get
