# permissions for end users to edit memcacheclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: memcachecluster-editor-role
rules:
- apiGroups:
  - flightdeck.t7.io
  resources:
  - memcacheclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - flightdeck.t7.io
  resources:
  - memcacheclusters/status
  verbs:
  - get
