# permissions for end users to edit mysqldatabases.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mysqldatabase-editor-role
rules:
- apiGroups:
  - flightdeck.t7.io
  resources:
  - mysqldatabases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - flightdeck.t7.io
  resources:
  - mysqldatabases/status
  verbs:
  - get
