# permissions for end users to view mysqldatabases.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mysqldatabase-viewer-role
rules:
- apiGroups:
  - flightdeck.t7.io
  resources:
  - mysqldatabases
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - flightdeck.t7.io
  resources:
  - mysqldatabases/status
  verbs:
  - get
