# permissions for end users to view phpapplications.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: phpapplication-viewer-role
rules:
- apiGroups:
  - flightdeck.t7.io
  resources:
  - phpapplications
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - flightdeck.t7.io
  resources:
  - phpapplications/status
  verbs:
  - get
