# permissions for end users to edit phpapplications.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: phpapplication-editor-role
rules:
- apiGroups:
  - flightdeck.t7.io
  resources:
  - phpapplications
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - flightdeck.t7.io
  resources:
  - phpapplications/status
  verbs:
  - get
