# permissions for end users to view phpcronjobs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: phpcronjob-viewer-role
rules:
- apiGroups:
  - flightdeck.t7.io
  resources:
  - phpcronjobs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - flightdeck.t7.io
  resources:
  - phpcronjobs/status
  verbs:
  - get
