# permissions for end users to edit phpcronjobs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: phpcronjob-editor-role
rules:
- apiGroups:
  - flightdeck.t7.io
  resources:
  - phpcronjobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - flightdeck.t7.io
  resources:
  - phpcronjobs/status
  verbs:
  - get
