# permissions for end users to edit phproutes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: phproute-editor-role
rules:
- apiGroups:
  - flightdeck.t7.io
  resources:
  - phproutes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - flightdeck.t7.io
  resources:
  - phproutes/status
  verbs:
  - get
