---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
  ##
  ## Base operator rules
  ##
  - apiGroups:
      - ""
    resources:
      - secrets
      - configmaps
      - services
      - pods
      - pods/exec
      - pods/log
      - persistentvolumeclaims
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - "batch"
    resources:
      - cronjobs
      - jobs
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - "networking.k8s.io"
    resources:
      - ingresses
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - apps
    resources:
      - deployments
      - daemonsets
      - replicasets
      - statefulsets
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  ##
  ## Rules for flightdeck.t7.io/v1, Kind: MySQLCluster
  ##
  - apiGroups:
      - flightdeck.t7.io
    resources:
      - mysqlclusters
      - mysqlclusters/status
      - mysqlclusters/finalizers
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  ##
  ## Rules for flightdeck.t7.io/v1, Kind: MySQLDatabase
  ##
  - apiGroups:
      - flightdeck.t7.io
    resources:
      - mysqldatabases
      - mysqldatabases/status
      - mysqldatabases/finalizers
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  ##
  ## Rules for flightdeck.t7.io/v1, Kind: MySQLUser
  ##
  - apiGroups:
      - flightdeck.t7.io
    resources:
      - mysqlusers
      - mysqlusers/status
      - mysqlusers/finalizers
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  ##
  ## Rules for flightdeck.t7.io/v1, Kind: MemcacheCluster
  ##
  - apiGroups:
      - flightdeck.t7.io
    resources:
      - memcacheclusters
      - memcacheclusters/status
      - memcacheclusters/finalizers
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  ##
  ## Rules for flightdeck.t7.io/v1, Kind: PhpApplication
  ##
  - apiGroups:
      - flightdeck.t7.io
    resources:
      - phpapplications
      - phpapplications/status
      - phpapplications/finalizers
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  ##
  ## Rules for flightdeck.t7.io/v1, Kind: Htpasswd
  ##
  - apiGroups:
      - flightdeck.t7.io
    resources:
      - htpasswds
      - htpasswds/status
      - htpasswds/finalizers
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  ##
  ## Rules for flightdeck.t7.io/v1, Kind: PhpRoute
  ##
  - apiGroups:
      - flightdeck.t7.io
    resources:
      - phproutes
      - phproutes/status
      - phproutes/finalizers
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  ##
  ## Rules for flightdeck.t7.io/v1, Kind: PhpCronjob
  ##
  - apiGroups:
      - flightdeck.t7.io
    resources:
      - phpcronjobs
      - phpcronjobs/status
      - phpcronjobs/finalizers
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  ##
  ## Rules for flightdeck.t7.io/v1, Kind: SolrCluster
  ##
  - apiGroups:
      - flightdeck.t7.io
    resources:
      - solrclusters
      - solrclusters/status
      - solrclusters/finalizers
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  ##
  ## Rules for flightdeck.t7.io/v1, Kind: SolrCollection
  ##
  - apiGroups:
      - flightdeck.t7.io
    resources:
      - solrcollections
      - solrcollections/status
      - solrcollections/finalizers
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  ##
  ## Rules for flightdeck.t7.io/v1, Kind: ZookeeperCluster
  ##
  - apiGroups:
      - flightdeck.t7.io
    resources:
      - zookeeperclusters
      - zookeeperclusters/status
      - zookeeperclusters/finalizers
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  ##
  ## Rules for flightdeck.t7.io/v1, Kind: SolrConfigset
  ##
  - apiGroups:
      - flightdeck.t7.io
    resources:
      - solrconfigsets
      - solrconfigsets/status
      - solrconfigsets/finalizers
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  ##
  ## Rules for flightdeck.t7.io/v1, Kind: SolrRole
  ##
  - apiGroups:
      - flightdeck.t7.io
    resources:
      - solrroles
      - solrroles/status
      - solrroles/finalizers
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  ##
  ## Rules for flightdeck.t7.io/v1, Kind: SolrUser
  ##
  - apiGroups:
      - flightdeck.t7.io
    resources:
      - solrusers
      - solrusers/status
      - solrusers/finalizers
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  ##
  ## Rules for flightdeck.t7.io/v1, Kind: TwemproxyCluster
  ##
  - apiGroups:
      - flightdeck.t7.io
    resources:
      - twemproxyclusters
      - twemproxyclusters/status
      - twemproxyclusters/finalizers
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
# +kubebuilder:scaffold:rules
