# permissions for end users to edit solrconfigsets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: solrconfigset-editor-role
rules:
- apiGroups:
  - flightdeck.t7.io
  resources:
  - solrconfigsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - flightdeck.t7.io
  resources:
  - solrconfigsets/status
  verbs:
  - get
