# permissions for end users to edit solrcores.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: solrcore-editor-role
rules:
- apiGroups:
  - flightdeck.t7.io
  resources:
  - solrcores
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - flightdeck.t7.io
  resources:
  - solrcores/status
  verbs:
  - get
