# permissions for end users to edit solrclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: solrcluster-editor-role
rules:
- apiGroups:
  - flightdeck.t7.io
  resources:
  - solrclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - flightdeck.t7.io
  resources:
  - solrclusters/status
  verbs:
  - get
