# permissions for end users to view solrcollections.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: solrcollection-viewer-role
rules:
- apiGroups:
  - flightdeck.t7.io
  resources:
  - solrcollections
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - flightdeck.t7.io
  resources:
  - solrcollections/status
  verbs:
  - get
