# permissions for end users to view solrconfigsets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: solrconfigset-viewer-role
rules:
- apiGroups:
  - flightdeck.t7.io
  resources:
  - solrconfigsets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - flightdeck.t7.io
  resources:
  - solrconfigsets/status
  verbs:
  - get
