# permissions for end users to view solrroles.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: solrrole-viewer-role
rules:
- apiGroups:
  - flightdeck.t7.io
  resources:
  - solrroles
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - flightdeck.t7.io
  resources:
  - solrroles/status
  verbs:
  - get
