# permissions for end users to edit solrusers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: solruser-editor-role
rules:
- apiGroups:
  - flightdeck.t7.io
  resources:
  - solrusers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - flightdeck.t7.io
  resources:
  - solrusers/status
  verbs:
  - get
