# permissions for end users to edit twemproxyclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: twemproxycluster-editor-role
rules:
- apiGroups:
  - flightdeck.t7.io
  resources:
  - twemproxyclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - flightdeck.t7.io
  resources:
  - twemproxyclusters/status
  verbs:
  - get
