# permissions for end users to view twemproxyclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: twemproxycluster-viewer-role
rules:
- apiGroups:
  - flightdeck.t7.io
  resources:
  - twemproxyclusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - flightdeck.t7.io
  resources:
  - twemproxyclusters/status
  verbs:
  - get
