---
- name: Delete the mysql writer service
  k8s:
    api_version: "v1"
    kind: "Service"
    name: "{{ ansible_operator_meta.name }}-writer"
    namespace: "{{ ansible_operator_meta.namespace }}"
    state: absent

- name: Delete the mysql writer statefulset
  k8s:
    api_version: "apps/v1"
    kind: "StatefulSet"
    name: "{{ ansible_operator_meta.name }}-writer"
    namespace: "{{ ansible_operator_meta.namespace }}"
    state: absent

- name: Delete the mysql writer configmap
  k8s:
    api_version: "v1"
    kind: "ConfigMap"
    name: "{{ ansible_operator_meta.name }}-config"
    namespace: "{{ ansible_operator_meta.namespace }}"
    state: absent

- name: Delete the mysql readers secret if operator created
  k8s:
    api_version: "v1"
    kind: "Secret"
    name: "{{ ansible_operator_meta.name + '-user' }}"
    namespace: "{{ ansible_operator_meta.namespace }}"
    state: absent
  when:
    - "(mysql_root_secret | default('')) == ''"

- name: Delete the mysql operator secret if operator created
  k8s:
    api_version: "v1"
    kind: "Secret"
    name: "{{ ansible_operator_meta.name + '-operator' }}"
    namespace: "{{ ansible_operator_meta.namespace }}"
    state: absent
  when:
    - "(mysql_root_secret | default('')) == ''"

- name: Delete the mysql root secret if operator created
  k8s:
    api_version: "v1"
    kind: "Secret"
    name: "{{ ansible_operator_meta.name + '-root' }}"
    namespace: "{{ ansible_operator_meta.namespace }}"
    state: absent
  when:
    - "(mysql_root_secret | default('')) == ''"
