---
- name: Generate the cluster name
  set_fact:
    _mysql_cluster_full_name: "{{ fullname_override | default(ansible_operator_meta.name + '-mysqlcluster') }}"

- name: Delete the mysql service
  k8s:
    api_version: "v1"
    kind: "Service"
    name: "{{ service.name | default(_mysql_cluster_full_name) }}"
    namespace: "{{ ansible_operator_meta.namespace }}"
    state: absent

- name: Delete the mysql statefulset
  k8s:
    api_version: "apps/v1"
    kind: "StatefulSet"
    name: "{{ _mysql_cluster_full_name }}"
    namespace: "{{ ansible_operator_meta.namespace }}"
    state: absent

- name: Delete the mysql configmap
  k8s:
    api_version: "v1"
    kind: "ConfigMap"
    name: "config-{{ _mysql_cluster_full_name }}"
    namespace: "{{ ansible_operator_meta.namespace }}"
    state: absent

- name: Delete the mysql readers secret if operator created
  k8s:
    api_version: "v1"
    kind: "Secret"
    name: "{{ 'user-' + _mysql_cluster_full_name }}"
    namespace: "{{ ansible_operator_meta.namespace }}"
    state: absent
  when:
    - "(mysql_root_secret | default('')) == ''"

- name: Delete the mysql operator secret if operator created
  k8s:
    api_version: "v1"
    kind: "Secret"
    name: "{{ 'operator-' + _mysql_cluster_full_name }}"
    namespace: "{{ ansible_operator_meta.namespace }}"
    state: absent
  when:
    - "(mysql_root_secret | default('')) == ''"

- name: Delete the mysql root secret if operator created
  k8s:
    api_version: "v1"
    kind: "Secret"
    name: "{{ 'root-' + _mysql_cluster_full_name }}"
    namespace: "{{ ansible_operator_meta.namespace }}"
    state: absent
  when:
    - "(mysql_root_secret | default('')) == ''"
