apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "flightdeck-operator.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: "{{ include "flightdeck-operator.name" . }}"
    app.kubernetes.io/name: "{{ include "flightdeck-operator.name" . }}"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
    app.kubernetes.io/component: "controller"
    helm.sh/chart: "{{ include "flightdeck-operator.chart" . }}"
    control-plane: controller-manager
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ template "flightdeck-operator.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      control-plane: controller-manager
  template:
    metadata:
      labels:
        app: "{{ template "flightdeck-operator.name" . }}"
        app.kubernetes.io/name: "{{ template "flightdeck-operator.name" . }}"
        app.kubernetes.io/instance: "{{ .Release.Name }}"
        app.kubernetes.io/component: "controller"
        app.kubernetes.io/managed-by: "{{ .Release.Service }}"
        helm.sh/chart: "{{ template "flightdeck-operator.chart" . }}"
        control-plane: "controller-manager"
{{- if .Values.podLabels }}
{{ toYaml .Values.podLabels | indent 8 }}
{{- end }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - args:
          - --secure-listen-address=0.0.0.0:8443
          - --upstream=http://127.0.0.1:8080/
          - --logtostderr=true
          - --v=10
          image: gcr.io/kubebuilder/kube-rbac-proxy:v0.5.0
          name: kube-rbac-proxy
          ports:
          - containerPort: 8443
            name: https
        - args:
          - --metrics-addr=127.0.0.1:8080
          - --enable-leader-election
          - --leader-election-id=flightdeck-operator
          env:
          - name: ANSIBLE_GATHERING
            value: explicit
          name: manager
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          # Hack around the app version best practice template until we get real
          # tags for the container.
          # image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          image: "{{ .Values.image.repository }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      terminationGracePeriodSeconds: 10
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
